FROM ubuntu:latest

# Update and install necessary packages
RUN apt update && apt upgrade -y && \
    apt install -y sudo build-essential

# Create a non-root user
RUN adduser --disabled-password --gecos "" developer && \
    echo "developer:1234" | chpasswd && \
    echo "root:1234" | chpasswd && \
    usermod -aG sudo developer

# Switch to the non-root user
USER developer
WORKDIR /home/developer
CMD ["/bin/bash"]

